### ISSUE TITLE
Bug: Access denied to edit record in dashboard (in sandbox)

### ISSUE THREAD

**Issue by marianneb** [jcu-eresearch/TDH-Research-Data-Catalogue#15]
I have a record in the dashboard that is owned by user "researcher" in the test site. I edited the record as admin and uploaded a file. I have then logged in as researcher and tried to edit the record (researcher is the owner) and get "Access Denied". 

When I try and edit the record again as admin I am getting

```
Page content template error: workflows/simpleworkflow
Traceback (most recent call last):
  File "default/default/scripts/workflows/simpleworkflow.py", line 74, in getFormHtml
	at com.googlecode.fascinator.portal.workflow.SimpleWorkflowHelper.getFormHtml(SimpleWorkflowHelper.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)

java.lang.NullPointerException: java.lang.NullPointerException
```

At this point I have no idea what is going on. 

https://eresearch.jcu.edu.au/researchdata/dashboard/detail/d1be4bfa063e0ada17996009cdd67165/

**Comment by ozej8y** [comment]
This has been retested. Unable to reproduce in eResearch Sandbox system.
