### ISSUE TITLE
Unable to edit record when pushed to Final Review

### ISSUE THREAD

**Issue by ozej8y** [jcu-eresearch/TDH-Research-Data-Catalogue#37]
The exception below being generated. 
The cause is because the localPid property is not set, and the $identifier value is not being constructed. This bug was introduced in the last change made to citation.vm

Page content template error: display/package-dataset/detail
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'replaceAll' in  class java.lang.String threw exception java.lang.NullPointerException at default/local/display/package-dataset/detail/preview/sections/citation.vm[line 39, column 33]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:337)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:284)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:262)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:342)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:263)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:175)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:212)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:247)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:175)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:263)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:175)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)

**Comment by ozej8y** [comment]
This issue has been fixed, then tested on the production machine.
